group: MY-ORGANIZATION
region: ap-northeast-1
instance:
  tag:
    key: Scheduled
    value: true
event:
  namePrefix: instance-control
  initiallyEnable: false
  startCron: cron(30 0 ? * MON-FRI *)
  stopCron: cron(30 12 ? * MON-FRI *)
slack:
  incoming-webhook-url: CHANGE-ME
  outgoing-webhook-token: CHANGE-ME